image: node:20

variables:
  SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN

stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_PROJECT_PATH_SLUG}
  paths:
    - node_modules/

before_script:
  - npm ci

build-job:
  stage: build
  script:
    - npm run build

unit-test-job:
  stage: test
  script:
    - npx vitest --coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  when: always

pages:
  stage: deploy
  script:
    - mkdir public/istanbul
    - cp -r coverage/* public/istanbul
    - echo '<html><head><title>Krisefikser Documentation</title></head><body><h1>Krisefikser Documentation</h1><ul><li><a href="istanbul/">Test Coverage Report</a></li></ul></body></html>' > public/index.html
  only:
    - dev

  artifacts:
    paths:
      - public