package stud.ntnu.no.krisefikser.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Entity
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "household_token")
public class HouseholdToken {
  /**
   * Unique identifier for the household token.
   * This is auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The token used for inviting to a household.
   * This should be a unique string.
   */
  @Column(nullable = false, unique = true)
  private String token;

  /**
   * The household associated with this household token.
   * One household can be associated with multiple tokens.
   */
  @ManyToOne()
  @JoinColumn(name = "household_id")
  private Household household;
}
