package stud.ntnu.no.krisefikser.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Entity
@Accessors(chain = true)
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "verification_token")
public class VerificationToken {
  /**
   * Unique identifier for the verification token.
   * This is auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The token used for verification.
   * This should be a unique string.
   */
  @Column(nullable = false,  unique = true)
  private String token;

  /**
   * The user associated with this verification token.
   */
  @OneToOne
  @JoinColumn(name = "user_id")
  private User user;
}
